### ISSUE TITLE
opencv requirement

### ISSUE THREAD

**Issue by kwea123** [Unity-Technologies/obstacle-tower-challenge#25]
I need to use opencv-python in my submission, however, this requires some dependencies to be installed via `apt get`:
```
apt-get install libsm6
apt-get install libxrender1
apt-get install libxext-dev
```
Therefore, I need to be able to add them in the Dockerfile when building the image, how can I do this?

**Comment by harperj** [comment]
Hi @kwea123 -- you can follow the [repo2docker instructions here](https://repo2docker.readthedocs.io/en/latest/config_files.html#apt-txt-install-packages-with-apt-get) and add the appropriate packages in the `apt.txt` file.

**Comment by kwea123** [comment]
Thank you. This works.
