### ISSUE TITLE
reset() before first run?

### ISSUE THREAD

**Issue by Holt59** [Unity-Technologies/obstacle-tower-challenge#30]
In the `run.py` code, the first `reset()` is done after the evaluation of `run_episode`. Would I get a penalty if I perform the reset before? E.g.:

```python
def run_evaluation(env):
    while not env.done_grading():
        env.reset()
        run_episode(env)
```

In particular, would this consider the first run as a failure with a reward of 0?

I have made some modifications to the `ObstacleTowerEnv`, part of which involve some initial setup in the `reset()` method.

**Comment by awjuliani** [comment]
Hi @Holt59 

@harperj Should be able to answer this for you.

**Comment by harperj** [comment]
Hi @Holt59 -- it should not be a problem if you run multiple resets before `step()`.  I'm going to close this issue but please feel free to reopen if you do see any problem with this in practice.
