### ISSUE TITLE
Error: 502: b'GitLab is not responding'

### ISSUE THREAD

**Issue by Sohojoe** [Unity-Technologies/obstacle-tower-challenge#31]
I've been unable to submit my agent. I get this error `502: b'GitLab is not responding'` after 15 mins or so.

https://gitlab.aicrowd.com/joe_booth/obstacle-tower-challenge/issues/12

**Comment by spMohanty** [comment]
I had responded on the individual thread. 
@sohojoe : can you please confirm and close the issue if this is not relevant anymore ?

**Comment by Sohojoe** [comment]
Sure - I think it is resolved. I think that the root cause of this was a timeout issue and that you addressed it over the weekend.
