### ISSUE TITLE
I am a new gitlab user..the upload file exceed size limit... 

### ISSUE THREAD

**Issue by breezeyuner** [Unity-Technologies/obstacle-tower-challenge#32]
the ckpt file of my model is about 80MB, I cannt push it gitlab since it is oversize.. 
I am new for gitlab, anyone could help me to handle it ? I have tried to make it done for 3 hours ;( Thanks ~

**Comment by spMohanty** [comment]
@breezeyuner : Please use git-lfs to check in the larger files.

**Comment by breezeyuner** [comment]
> 
> 
> @breezeyuner : Please use git-lfs to check in the larger files.

Thanks，I will try it ASAP~~~
