### ISSUE TITLE
What is the correct directory structure for submitting agent?

### ISSUE THREAD

**Issue by callenshaw** [Unity-Technologies/obstacle-tower-challenge#36]
Hi very last-minute issue I'm having with my submission. I have no clue how to structure my directory so that it actually uses my trained agent. I see "run.sh" which calls "run.py", but how does this relate to the GCP example? Specifically, if I trained my agent with this command:

`python -um dopamine.discrete_domains.train  --base_dir=/tmp/dopamine  --gin_files='dopamine/agents/rainbow/configs/rainbow_otc.gin'`

Then what edits to run.sh/py do I need to make, and/or where do I copy the dopamine files, such that it works correctly in the docker setup? Thanks for any help.

**Comment by callenshaw** [comment]
Well this was all a big waste of time. Considering the main tutorial was to use dopamine on GCP, the many issues I can't resolve, mostly unrelated to the actual ML challenge, have buried me. I wish there had been some more useful answers on these topics:

https://discourse.aicrowd.com/t/using-dopamine-trained-model/912
https://discourse.aicrowd.com/t/docker-not-running-environment/942
https://discourse.aicrowd.com/t/admin-good-news-for-dopamine-lovers/655
https://discourse.aicrowd.com/t/submission-dir-structure-files/959
https://github.com/google/dopamine/issues/95

I'd still love to know how one is supposed to turn the GCP training regiment into a working submission, just for my own education... I'm seeing a lot of comments elsewhere about timeout issues and dopamine not working well for this in general, so I can't even tell what I need to fix versus work around. Its been fun though, better luck next time I suppose :(

**Comment by awjuliani** [comment]
Hi @callenshaw,

I am sorry that you weren't able to get a submission working in time. In potential future contests we will do our best to provide more thorough instructions.
