### ISSUE TITLE
Code entrypoint in the evaluator

### ISSUE THREAD

**Issue by spMohanty** [Unity-Technologies/obstacle-tower-challenge#9]
The documentation currently uses `/home/otc/run.sh` as the code entrypoint. While the evaluator uses `/home/aicrowd/run.sh` as the entrypoint. 

This will cause quite some confusion in cases wherer participants drop in a Dockerfile at the root of the repositorry, to override the image building of `aicrowd-repo2docker`. In which case, then would need to ensure that the entrypoint that the evaluator uses actually exists. 

Hence, I believe its best to consistently use the `/home/aicrowd/run.sh` as the entrypoint in the local build scripts and docs.

**Comment by harperj** [comment]
Merged your PR which addresses this issue.
